### ISSUE TITLE
[Pixel Fold] When using upside-down, screen flips when navigating to camera screen

### ISSUE THREAD

**Issue by JolandaVerhoef** [android/socialite#1]
- Run the app on a Pixel Fold (API 34) emulator
- Set the foldable to half-open and in "virtual sensors" set the screen rotation to 180 degrees:
<img width="383" alt="Screenshot 2023-12-15 at 09 45 55" src="https://github.com/android/socialite/assets/6952116/0222cfe7-204f-4908-894c-65b4d88a1248"><img width="243" alt="Screenshot 2023-12-15 at 09 46 34" src="https://github.com/android/socialite/assets/6952116/6278d904-8f36-4328-9d0c-7767787ea408">

- Navigate to Sheep chat
- Press the camera icon

Expected:
Camera screen is opened in the same orientation

Actual:
The screen turns 180 degrees

https://github.com/android/socialite/assets/6952116/1959e2eb-ac13-4607-83e6-cfd377cda74b

**Comment by donovanfm** [comment]
Hey, Jolanda. Thanks for reporting this. However, it might not be something we can fix. The camera screen is not like other UIs, in that the layout shouldn't change when the device is rotated. Here are some reasons. 

1) The main UI component is the camera preview, which we want to be as big as possible. Since the camera sensor and screen are not squares (and [the long edge of the camera sensor must be on the long edge of the screen](https://source.android.com/docs/compatibility/14/android-14-cdd#755_camera_orientation)), the default orientation is the best fit, which on most devices is portrait.
2) The shutter button and other controls should be in a predictable place. Even a phone rotation (or acceleration change from being on a train, etc.) shouldn't move the shutter button. This behavior even matches the Pixel native camera. If you open it with the phone upside down, the shutter button is at the top and all of the button labels are upside down.
3) Not all devices define the default orientation as portrait. For example, the Pixel Fold has a default orientation of portrait when it's folded, and landscape when it's unfolded. This is why [we opted for SCREEN_ORIENTATION_NOSENSOR](https://github.com/android/socialite/blob/main/app/src/main/java/com/google/android/samples/socialite/ui/Main.kt#L74) on the camera screen instead of SCREEN_ORIENTATION_SENSOR_PORTRAIT or SCREEN_ORIENTATION_USER_PORTRAIT.

All of these considerations combined are why we went with SCREEN_ORIENTATION_NOSENSOR. I checked with @romanofranz about updating SociaLite to support 0º and 180º orientations, but given the number of devices with different default orientations, he's concerned we'd introduce more bugs by trying that.

I'll close this as WAI for now, but happy to discuss further if you have more thoughts.

**Comment by alexvanyo** [comment]
> This behavior even matches the Pixel native camera.

This doesn't match the Pixel native camera behavior when using the inner screen of the Pixel Fold or the Pixel Tablet. In either of those situations, the shutter button does move as the device is rotated.

**Comment by donovanfm** [comment]
Thanks for the additional context, Alex. I updated my comment above to incorporate that. I still believe this is WAI from a camera perspective, but if the Large Screens team wants to author a fix that won't introduce more bugs on different form factors, I'd be happy to take a look.

**Comment by romanofranz** [comment]
I add a patch in https://github.com/android/socialite/pull/26.
We are not changing the position of the shutter at this team, but at least the "video/photo" text now rotates for better readability in different orientations
